# Generated by Django 3.1.4 on 2021-02-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='playlist_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
