# Generated by Django 3.1.4 on 2021-02-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210222_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='progress_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
