# Generated by Django 3.1.4 on 2021-04-05 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210226_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='most_recent_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='most_recent_name', to='core.room'),
        ),
    ]
