# Generated by Django 3.1.4 on 2021-04-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_most_recent_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='playlist_image_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
