# Generated by Django 3.1.4 on 2021-04-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_room_playlist_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
