# Generated by Django 3.1.4 on 2021-04-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_authorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_color',
            field=models.CharField(default='o7ace5', max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='icon_color',
            field=models.CharField(default='ffffff', max_length=6),
        ),
    ]
