# Generated by Django 3.1.4 on 2021-04-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210407_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background_color',
            field=models.CharField(default='07ace5', max_length=6),
        ),
    ]
