# Generated by Django 3.1.4 on 2021-05-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210503_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='offset',
        ),
        migrations.RemoveField(
            model_name='room',
            name='playing',
        ),
        migrations.RemoveField(
            model_name='room',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='room',
            name='progress_time',
        ),
        migrations.AddField(
            model_name='playlist',
            name='playing',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
