# Generated by Django 3.1.4 on 2021-05-05 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210505_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_index', models.IntegerField(blank=True, default=0)),
                ('progress_ms', models.IntegerField(blank=True, default=0, null=True)),
                ('last_action', models.DateTimeField(blank=True, null=True)),
                ('playing', models.BooleanField(blank=True, default=False)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
            ],
        ),
    ]
