# Generated by Django 3.1.4 on 2021-05-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210503_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='last_action',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
