# Generated by Django 3.1.4 on 2021-05-08 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_playlist_last_song_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='offset',
        ),
        migrations.RemoveField(
            model_name='room',
            name='playing',
        ),
        migrations.RemoveField(
            model_name='room',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='room',
            name='progress_time',
        ),
    ]
