# Generated by Django 3.1.4 on 2021-05-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210503_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='progress_ms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='last_action',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
