# Generated by Django 3.1.4 on 2021-05-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tag_line',
            field=models.CharField(default='Syncer', max_length=50),
        ),
    ]
