# Generated by Django 3.1.4 on 2021-05-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userprofile_tag_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='banner_color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
