# Generated by Django 3.1.4 on 2021-05-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_room_banner_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='invite_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='invite_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='mode',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('closed', 'Closed')], default='private', max_length=50),
        ),
    ]
