# Generated by Django 3.1.4 on 2021-05-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210513_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='new_user',
            field=models.BooleanField(default=True),
        ),
    ]
