# Generated by Django 3.1.4 on 2021-05-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_userprofile_new_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='new_room',
            field=models.BooleanField(default=True),
        ),
    ]
