# Generated by Django 3.1.4 on 2021-05-18 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_room_new_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='inactive_users',
            field=models.ManyToManyField(blank=True, related_name='inactive_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
