# Generated by Django 3.1.4 on 2021-05-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_room_inactive_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='new_room',
        ),
    ]
