# Generated by Django 3.1.4 on 2021-05-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_room_new_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='banner_color',
            field=models.CharField(blank=True, default='141414', max_length=6, null=True),
        ),
    ]
