# Generated by Django 3.1.4 on 2021-07-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_userprofile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='online_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
