# Generated by Django 3.1.4 on 2021-07-13 23:49

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210705_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_large',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[800, 800], upload_to='large/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_medium',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[500, 500], upload_to='medium/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_small',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[200, 200], upload_to='small/'),
        ),
    ]
