# Generated by Django 3.1.4 on 2021-07-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20210713_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='background_color',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='icon_color',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='icon_image',
        ),
    ]
