# Generated by Django 3.1.4 on 2021-07-16 18:11

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20210715_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_large',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[800, 800], upload_to='large'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image_medium',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[500, 500], upload_to='medium'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image_small',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[200, 200], upload_to='small'),
        ),
    ]
