# Generated by Django 3.1.4 on 2021-07-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20210716_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to='large'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to='medium'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='small'),
        ),
    ]
