# Generated by Django 3.1.4 on 2021-07-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20210716_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image_large',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image_medium',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image_small',
        ),
    ]
