# Generated by Django 3.1.4 on 2021-07-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20210716_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='NothingTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
