# Generated by Django 3.1.4 on 2021-07-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_nothingtwo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NothingTwo',
        ),
    ]
