# Generated by Django 3.1.4 on 2021-07-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_delete_nothingtwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepicture',
            name='large',
            field=models.ImageField(blank=True, null=True, upload_to='large'),
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='medium',
            field=models.ImageField(blank=True, null=True, upload_to='medium'),
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='small',
            field=models.ImageField(blank=True, null=True, upload_to='small'),
        ),
    ]
