# Generated by Django 3.1.4 on 2021-07-16 19:55

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20210716_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepicture',
            name='large',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[800, 800], upload_to='large'),
        ),
        migrations.AlterField(
            model_name='userprofilepicture',
            name='medium',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[500, 500], upload_to='medium'),
        ),
        migrations.AlterField(
            model_name='userprofilepicture',
            name='small',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[200, 200], upload_to='small'),
        ),
    ]
